# Generated by Django 4.2 on 2024-01-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0006_customuser_birth_date_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='管理サイトへのログインの権利を判断します', verbose_name='staff status'),
        ),
    ]
