# Generated by Django 4.2 on 2024-01-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0007_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='学年'),
        ),
    ]
