# Generated by Django 4.2 on 2024-01-13 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0009_rename_date_of_birth_customuser_birth_of_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default=1, max_length=20, verbose_name='ニックネーム'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
    ]
