# Generated by Django 5.0.1 on 2024-01-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0010_remove_customuser_username_customuser_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test_year',
            field=models.CharField(blank=True, choices=[('2024', '2024年度'), ('2025', '2025年度'), ('2026', '2026年度'), ('2027', '2027年度'), ('2028', '2028年度')], max_length=10, null=True, verbose_name='国試受験年度'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prefecture',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='都道府県'),
        ),
    ]
