# Generated by Django 5.0.1 on 2024-01-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0011_customuser_test_year_alter_customuser_prefecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='test_year',
            field=models.CharField(choices=[('2024', '2024年度'), ('2025', '2025年度'), ('2026', '2026年度'), ('2027', '2027年度'), ('2028', '2028年度')], default=1, max_length=10, verbose_name='国試受験年度'),
            preserve_default=False,
        ),
    ]
