# Generated by Django 5.0.1 on 2024-01-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0016_remove_comment_author_remove_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='ニックネーム'),
        ),
    ]
