# Generated by Django 5.0.1 on 2024-01-23 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0019_post_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-last_commented_at']},
        ),
    ]
