# Generated by Django 5.0.1 on 2024-01-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0022_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('月', '月曜日'), ('火', '火曜日'), ('水', '水曜日'), ('木', '木曜日'), ('金', '金曜日')], max_length=2)),
                ('period', models.IntegerField(choices=[(1, '1限（午前）'), (2, '2限（午前）'), (3, '3限（午後）'), (4, '4限（午後）'), (5, '5限（夜間）'), (6, '6限（夜間）')])),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
