# Generated by Django 5.0.1 on 2024-01-26 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0023_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('field', models.CharField(choices=[('Field 1', '分野1'), ('Field 2', '分野2')], max_length=50)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.IntegerField(choices=[(1, '1限'), (2, '2限'), (3, '3限'), (4, '4限'), (5, '5限'), (6, '6限')]),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt_kokushi.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('total_questions_attempted', models.IntegerField(default=0)),
                ('total_correct_answers', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
