# Generated by Django 5.0.1 on 2024-01-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0024_question_alter_timetable_period_useranswer_userscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分野名')),
                ('description', models.TextField(verbose_name='説明')),
                ('icon', models.ImageField(upload_to='field_icons/', verbose_name='アイコン')),
            ],
        ),
    ]
