# Generated by Django 4.2 on 2024-01-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0025_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='field',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='field_icons/'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Subfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subfield_icons/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt_kokushi.field')),
            ],
        ),
    ]
