# Generated by Django 4.2 on 2024-01-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0026_alter_field_description_alter_field_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='field',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='field_icons/', verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100, verbose_name='分野名'),
        ),
        migrations.AlterField(
            model_name='subfield',
            name='description',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='subfield',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='subfield_icons/', verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='subfield',
            name='name',
            field=models.CharField(max_length=100, verbose_name='分野名'),
        ),
    ]
