# Generated by Django 5.0.1 on 2024-01-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0027_alter_field_description_alter_field_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub2field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_detailed_selection', models.BooleanField(default=False, verbose_name='さらに詳細な分野選択')),
                ('name', models.CharField(max_length=100, verbose_name='分野名')),
                ('description', models.TextField(verbose_name='説明')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subfield_icons/', verbose_name='アイコン')),
            ],
        ),
    ]
