# Generated by Django 5.0.1 on 2024-01-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0029_sub2field_subfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfield',
            name='has_detailed_selection',
            field=models.BooleanField(default=False, verbose_name='さらに詳細な分野選択を可能にする'),
        ),
    ]
