# Generated by Django 5.0.1 on 2024-02-06 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0039_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('field', models.CharField(max_length=100, verbose_name='分野')),
                ('sub_field', models.CharField(blank=True, max_length=100, verbose_name='詳細分野')),
                ('point', models.IntegerField(choices=[(1, '1点'), (3, '3点')], verbose_name='配点')),
                ('question_number', models.IntegerField(verbose_name='問題番号')),
                ('answer_time', models.IntegerField(verbose_name='回答時間（秒）')),
                ('question_text', models.TextField(verbose_name='問題文')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='quiz_questions/', verbose_name='問題画像')),
                ('answer_text', models.TextField(verbose_name='解答分')),
                ('answer_video_url', models.URLField(blank=True, null=True, verbose_name='解答動画URL')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='ユーザーの回答')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='回答日時')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt_kokushi.exam', verbose_name='問題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
