# Generated by Django 5.0.1 on 2024-02-06 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0040_quizquestion_questionuseranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='year',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pt_kokushi.exam', verbose_name='年度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(unique=True, verbose_name='年度'),
        ),
        migrations.AlterField(
            model_name='questionuseranswer',
            name='exam_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt_kokushi.quizquestion', verbose_name='問題'),
        ),
    ]
