# Generated by Django 5.0.1 on 2024-02-07 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0041_remove_quizquestion_year_quizquestion_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ブックマーク日時')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt_kokushi.quizquestion', verbose_name='ブックマークした問題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
