# Generated by Django 5.0.1 on 2024-02-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0043_choice_quizuseranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': '国試「ブックマーク」', 'verbose_name_plural': '国試「ブックマーク」'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '国試「回答選択肢」', 'verbose_name_plural': '国試「回答選択肢」'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '掲示板（コメント）', 'verbose_name_plural': '掲示板（コメント）'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'カレンダー', 'verbose_name_plural': 'カレンダー'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': '国試「年度追加」', 'verbose_name_plural': '国試「年度追加」'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': '基礎学習「分野追加」', 'verbose_name_plural': '基礎学習「分野追加」'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '基礎学習「問題作成」', 'verbose_name_plural': '基礎学習「問題作成」'},
        ),
        migrations.AlterModelOptions(
            name='questionuseranswer',
            options={'verbose_name': '国試「ユーザーの回答」', 'verbose_name_plural': '国試「ユーザーの回答」'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': '国試「問題作成」', 'verbose_name_plural': '国試「問題作成」'},
        ),
        migrations.AlterModelOptions(
            name='sub2field',
            options={'verbose_name': '基礎学習「補足詳細分野追加」', 'verbose_name_plural': '基礎学習「補足詳細分野追加」'},
        ),
        migrations.AlterModelOptions(
            name='subfield',
            options={'verbose_name': '基礎学習「詳細分野追加」', 'verbose_name_plural': '基礎学習「詳細分野追加」'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': '時間割', 'verbose_name_plural': '時間割'},
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'ToDoリスト', 'verbose_name_plural': 'ToDoリスト'},
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='answer_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='回答時間（秒）'),
        ),
    ]
