# Generated by Django 4.2 on 2024-02-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0044_alter_bookmark_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KokushiField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分野名')),
            ],
            options={
                'verbose_name': '分野',
                'verbose_name_plural': '分野',
            },
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='sub_field',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt_kokushi.kokushifield', verbose_name='分野'),
        ),
    ]
