# Generated by Django 4.2 on 2024-02-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0045_kokushifield_remove_quizquestion_sub_field_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kokushifield',
            options={'verbose_name': '国試分野', 'verbose_name_plural': '国試分野'},
        ),
    ]
