# Generated by Django 4.2 on 2024-02-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0046_alter_kokushifield_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='new_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pt_kokushi.kokushifield', verbose_name='分野'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='旧分野'),
        ),
    ]
