# Generated by Django 4.2 on 2024-02-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0048_remove_quizquestion_new_field_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KokushiField',
        ),
    ]
