# Generated by Django 4.2 on 2024-02-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0049_delete_kokushifield'),
    ]

    operations = [
        migrations.CreateModel(
            name='KokushiField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分野名')),
            ],
            options={
                'verbose_name': '国試分野',
                'verbose_name_plural': '国試分野',
            },
        ),
    ]
