# Generated by Django 4.2 on 2024-02-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0050_kokushifield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pt_kokushi.kokushifield', verbose_name='分野'),
        ),
    ]
