# Generated by Django 4.2 on 2024-02-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0051_alter_quizquestion_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='field',
        ),
    ]
