# Generated by Django 5.0.1 on 2024-02-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0052_remove_quizquestion_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kokushifield',
            options={'verbose_name': '分野', 'verbose_name_plural': '分野'},
        ),
    ]
