# Generated by Django 5.0.1 on 2024-02-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0054_add_initial_kokushifield_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KokushiField',
        ),
    ]
