# Generated by Django 5.0.1 on 2024-02-13 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0056_kokushifield_quizquestion_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kokushifield',
            options={'verbose_name': '国試「分野追加」', 'verbose_name_plural': '国試「分野追加」'},
        ),
        migrations.AddField(
            model_name='quizuseranswer',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizuseranswer',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='QuestionUserAnswer',
        ),
    ]
