# Generated by Django 5.0.1 on 2024-02-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0059_kokushiquizsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='time',
            field=models.CharField(choices=[('午前', '午前'), ('午後', '午後')], default='午前', max_length=2, verbose_name='時間帯'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt_kokushi.kokushifield', verbose_name='分野'),
        ),
    ]
