# Generated by Django 5.0.1 on 2024-02-21 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0060_quizquestion_time_alter_quizquestion_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='time',
            field=models.CharField(choices=[('午前', '午前'), ('午後', '午後')], default='午前', max_length=2, verbose_name='午前・午後'),
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(verbose_name='学習日')),
                ('study_duration', models.IntegerField(verbose_name='学習時間（分）')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
