# Generated by Django 4.2 on 2024-02-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0061_alter_quizquestion_time_studylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylog',
            name='study_content',
            field=models.TextField(default='', verbose_name='学習内容'),
        ),
    ]
