# Generated by Django 4.2 on 2024-03-01 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0064_alter_timetable_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuseranswer',
            name='quiz_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pt_kokushi.kokushiquizsession', verbose_name='クイズセッション'),
        ),
    ]
