# Generated by Django 4.2 on 2024-03-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0067_alter_column_options_explanationimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explanationimage',
            options={'verbose_name': '国試「解説用画像」', 'verbose_name_plural': '国試「解説用画像」'},
        ),
    ]
