# Generated by Django 4.2 on 2024-03-06 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0068_alter_explanationimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='解説文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='explanations/images/', verbose_name='解説画像')),
                ('video_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='解説動画URL')),
                ('choice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='pt_kokushi.choice')),
            ],
            options={
                'verbose_name': '国試「選択肢解説」',
                'verbose_name_plural': '国試「選択肢解説」',
            },
        ),
    ]
