# Generated by Django 4.2 on 2024-03-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0071_aozorabook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aozorabook',
            options={'verbose_name': '青空文庫', 'verbose_name_plural': '青空文庫'},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'verbose_name': 'chatGPT小説', 'verbose_name_plural': 'chatGPT小説'},
        ),
    ]
