# Generated by Django 4.2 on 2024-03-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0074_pdfcategory_pdfdocument_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='kokushiquizsession',
            name='end_question_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='終了問題ID'),
        ),
        migrations.AddField(
            model_name='kokushiquizsession',
            name='start_question_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='開始問題ID'),
        ),
    ]
