# Generated by Django 4.2 on 2024-03-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0076_inquiry_alter_kokushifield_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'お問い合わせ', 'verbose_name_plural': 'お問い合わせ'},
        ),
    ]
