# Generated by Django 4.2 on 2024-03-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0077_alter_inquiry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='分野')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('file', models.FileField(upload_to='learning_materials/', verbose_name='ファイル')),
            ],
            options={
                'verbose_name': '学習資料',
                'verbose_name_plural': '学習資料',
            },
        ),
    ]
