# Generated by Django 4.2 on 2024-04-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_kokushi', '0078_learningmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_year', models.IntegerField(verbose_name='受験年度')),
                ('applicants_total', models.IntegerField(verbose_name='出願者数(総合)')),
                ('applicants_new_graduates', models.IntegerField(verbose_name='出願者数(新卒者)')),
                ('examinees_total', models.IntegerField(verbose_name='受験者数(総合)')),
                ('examinees_new_graduates', models.IntegerField(verbose_name='受験者数(新卒者)')),
                ('passers_total', models.IntegerField(verbose_name='合格者数(総合)')),
                ('passers_new_graduates', models.IntegerField(verbose_name='合格者数(新卒)')),
            ],
        ),
    ]
